export const IMAGES = {
  LOGO: "/images/logo.png",
  LOGO_CIRCLE: "/images/logo-circle.png",
  HERO_BG: "/images/hero-bg.jpg",
  RESULT_BG: "/images/result-bg.jpg",
  ADVANTAGES_IMAGE: "/images/advantages-image.jpg",
  PROBLEM_IMAGE: "/images/problem-image.jpg",
  SERVICE_TREES: "/images/service-trees.jpg",
  SERVICE_GRASS: "/images/service-grass.jpg",
  SERVICE_SPRAYING: "/images/service-spraying.jpg",
  SERVICE_REMOVAL: "/images/service-removal.jpg",
  SERVICE_CONSTRUCTION: "/images/service-construction.jpg",
  CLIENT_1: "/images/client-1.jpg",
  CLIENT_2: "/images/client-2.jpg",
  CLIENT_3: "/images/client-3.jpg",
  ELEMENT: "/images/element.png",
  RED_FLORAL_ORNAMENT_WHITE_BACKGROUND_EMBROIDERY: "/images/red-floral-ornament-white-background-embroidery.png",
} as const;
