export const IMAGES = {
  LOGO: "https://bvuagbjdedtfmvitrfpa.supabase.co/storage/v1/object/public/images/logos/logo.png",
  LOGO_CIRCLE: "https://bvuagbjdedtfmvitrfpa.supabase.co/storage/v1/object/public/images/logos/logo-circle.png",
  HERO_BG: "https://bvuagbjdedtfmvitrfpa.supabase.co/storage/v1/object/public/images/backgrounds/hero-bg.jpg",
  RESULT_BG: "https://bvuagbjdedtfmvitrfpa.supabase.co/storage/v1/object/public/images/backgrounds/result-bg.jpg",
  ADVANTAGES_IMAGE: "https://bvuagbjdedtfmvitrfpa.supabase.co/storage/v1/object/public/images/sections/advantages-image.jpg",
  PROBLEM_IMAGE: "https://bvuagbjdedtfmvitrfpa.supabase.co/storage/v1/object/public/images/sections/problem-image.jpg",
  SERVICE_TREES: "https://bvuagbjdedtfmvitrfpa.supabase.co/storage/v1/object/public/images/services/service-trees.jpg",
  SERVICE_GRASS: "https://bvuagbjdedtfmvitrfpa.supabase.co/storage/v1/object/public/images/services/service-grass.jpg",
  SERVICE_SPRAYING: "https://bvuagbjdedtfmvitrfpa.supabase.co/storage/v1/object/public/images/services/service-spraying.jpg",
  SERVICE_REMOVAL: "https://bvuagbjdedtfmvitrfpa.supabase.co/storage/v1/object/public/images/services/service-removal.jpg",
  SERVICE_CONSTRUCTION: "https://bvuagbjdedtfmvitrfpa.supabase.co/storage/v1/object/public/images/services/service-construction.jpg",
  CLIENT_1: "https://bvuagbjdedtfmvitrfpa.supabase.co/storage/v1/object/public/images/clients/client-1.jpg",
  CLIENT_2: "https://bvuagbjdedtfmvitrfpa.supabase.co/storage/v1/object/public/images/clients/client-2.jpg",
  CLIENT_3: "https://bvuagbjdedtfmvitrfpa.supabase.co/storage/v1/object/public/images/clients/client-3.jpg",
  ELEMENT: "https://bvuagbjdedtfmvitrfpa.supabase.co/storage/v1/object/public/images/elements/element.png",
  RED_FLORAL_ORNAMENT_WHITE_BACKGROUND_EMBROIDERY: "https://bvuagbjdedtfmvitrfpa.supabase.co/storage/v1/object/public/images/elements/red-floral-ornament-white-background-embroidery.png",
} as const;
