export const IMAGES = {
  LOGO: "/images/logos/logo.png",
  LOGO_CIRCLE: "/images/logos/logo-circle.png",
  HERO_BG: "/images/backgrounds/hero-bg.jpg",
  RESULT_BG: "/images/backgrounds/result-bg.jpg",
  ADVANTAGES_IMAGE: "/images/sections/advantages-image.jpg",
  PROBLEM_IMAGE: "/images/sections/problem-image.jpg",
  SERVICE_TREES: "/images/services/service-trees.jpg",
  SERVICE_GRASS: "/images/services/service-grass.jpg",
  SERVICE_SPRAYING: "/images/services/service-spraying.jpg",
  SERVICE_REMOVAL: "/images/services/service-removal.jpg",
  SERVICE_CONSTRUCTION: "/images/services/service-construction.jpg",
  CLIENT_1: "/images/clients/client-1.jpg",
  CLIENT_2: "/images/clients/client-2.jpg",
  CLIENT_3: "/images/clients/client-3.jpg",
  ELEMENT: "/images/elements/element.png",
  RED_FLORAL_ORNAMENT_WHITE_BACKGROUND_EMBROIDERY: "/images/elements/red-floral-ornament-white-background-embroidery.png",
} as const;
